version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.9-management    
    hostname: rabbit
    container_name: rabbitmq3.9
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./data:/var/lib/rabbitmq3
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
networks:
  default:
    external:
      name: minikube