version: "2"
services:
  nacos:
    image: nacos/nacos-server:2.0.2
    container_name: nacos-standalone
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    volumes:
     - ./logs/:/home/nacos/logs
     # - ./data/:/home/nacos/data/
     # - ./conf/:/home/nacos/conf/
    ports:
      - "8848:8848"
      - "9848:9848"
