version: '3'
services:
  db:
    image: 'docker.io/mysql:5.7'
    restart: always
    container_name: mysql
    volumes:
      - ./data:/var/lib/mysql
      # - ./mysql.cnf:/etc/mysql/mysql.cnf
      - ./init:/docker-entrypoint-initdb.d/
    ports:
      - '3306:3306'  #“宿主机端口号：容器内端口号”
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_USER: 'test'  # 创建普通用户
      MYSQL_PASSWORD: '123456'     #普通用户密码
      MYSQL_DATABASE:  'test'  #创建一个库

#networks:
#  default:
#    external:
#      name: minikube
