version: "3.1"
services:
  redis:
    image: redis:4
    environment:
      TZ: Asia/Shanghai
    ports:
      - 6379:6379
    command: ["redis-server","/etc/redis/redis.conf"]
    restart: always
    volumes:
      - ./conf:/etc/redis/
      - ./data:/data
      
# networks:
#   default:
#     external:
#       name: minikube